var searchData=
[
  ['remove_5fsurplus_5ffrom_5fcolumn',['remove_surplus_from_column',['../classSimplex__method__calculator.html#ab5bb8261a97db63956fad14a0c1f0f05',1,'Simplex_method_calculator']]],
  ['reply',['reply',['../classDb__loader.html#aa845f4b8ed46a42205b214db633ff141',1,'Db_loader']]],
  ['reply2',['reply2',['../classDb__loader.html#abe12d8b3b8b23aeb4c70dc8cb103b33e',1,'Db_loader']]],
  ['req',['req',['../classDb__loader.html#a3bf15a8ed1216c614b030610cebabaeb',1,'Db_loader']]],
  ['result',['result',['../classresult__reporter__dialog.html#abec7c912a4cada9f1468fa797891cf03',1,'result_reporter_dialog::result()'],['../classResult__Reporter__Minimal.html#aed1a497f319d5bf551f37d576a197da7',1,'Result_Reporter_Minimal::result()'],['../classResult__Reporter__Default.html#a654d38fe6778e3b1f29af621fb751312',1,'Result_Reporter_Default::result()']]],
  ['result_5freport_5fplugin_5finterface',['Result_Report_Plugin_Interface',['../classResult__Report__Plugin__Interface.html',1,'']]],
  ['result_5freport_5fplugin_5finterface_2eh',['result_report_plugin_interface.h',['../Result__Reporter__minimal_2result__report__plugin__interface_8h.html',1,'(Global Namespace)'],['../Result__Reporter__no1_2result__report__plugin__interface_8h.html',1,'(Global Namespace)'],['../simplex__app_2result__report__plugin__interface_8h.html',1,'(Global Namespace)']]],
  ['result_5freport_5fplugin_5floader',['Result_Report_plugin_Loader',['../classResult__Report__plugin__Loader.html',1,'Result_Report_plugin_Loader'],['../classMainWindow.html#a238e01801020c0ea22d30739cbfc35f1',1,'MainWindow::Result_Report_plugin_Loader()'],['../classResult__Report__plugin__Loader.html#a6276745d1351cafa6ba2a08e1909240c',1,'Result_Report_plugin_Loader::Result_Report_plugin_Loader()']]],
  ['result_5freport_5fplugin_5floader_2ecpp',['result_report_plugin_loader.cpp',['../result__report__plugin__loader_8cpp.html',1,'']]],
  ['result_5freport_5fplugin_5floader_2eh',['result_report_plugin_loader.h',['../result__report__plugin__loader_8h.html',1,'']]],
  ['result_5freporter_5fdefault',['Result_Reporter_Default',['../classResult__Reporter__Default.html',1,'Result_Reporter_Default'],['../classResult__Reporter__Default.html#a220d065072f8aa3ef351094b1710560e',1,'Result_Reporter_Default::Result_Reporter_Default()']]],
  ['result_5freporter_5fdefault_2ecpp',['result_reporter_default.cpp',['../result__reporter__default_8cpp.html',1,'']]],
  ['result_5freporter_5fdefault_2eh',['result_reporter_default.h',['../result__reporter__default_8h.html',1,'']]],
  ['result_5freporter_5fdialog',['result_reporter_dialog',['../classresult__reporter__dialog.html',1,'result_reporter_dialog'],['../classresult__reporter__dialog.html#ad6b12890998c80ec5f69ee28ad28e533',1,'result_reporter_dialog::result_reporter_dialog(QStandardItemModel *indulo, QStandardItemModel *result, int lsz, QString pivot_modszer, QString vari_name, QWidget *parent=nullptr)'],['../classresult__reporter__dialog.html#a2edb2abb1360433138892c9fc2236506',1,'result_reporter_dialog::result_reporter_dialog(QStandardItemModel *indulo, QStandardItemModel *result, int lsz, const QString &amp;pivot_modszer, const QString &amp;vari_name, QWidget *parent=nullptr)']]],
  ['result_5freporter_5fdialog_2ecpp',['result_reporter_dialog.cpp',['../Result__Reporter__minimal_2result__reporter__dialog_8cpp.html',1,'(Global Namespace)'],['../Result__Reporter__no1_2result__reporter__dialog_8cpp.html',1,'(Global Namespace)']]],
  ['result_5freporter_5fdialog_2eh',['result_reporter_dialog.h',['../Result__Reporter__minimal_2result__reporter__dialog_8h.html',1,'(Global Namespace)'],['../Result__Reporter__no1_2result__reporter__dialog_8h.html',1,'(Global Namespace)']]],
  ['result_5freporter_5fminimal',['Result_Reporter_Minimal',['../classResult__Reporter__Minimal.html',1,'Result_Reporter_Minimal'],['../classResult__Reporter__Minimal.html#ac8df5caefa98c8a146bb5cf667febb73',1,'Result_Reporter_Minimal::Result_Reporter_Minimal()']]],
  ['result_5freporter_5fminimal_2ecpp',['result_reporter_minimal.cpp',['../result__reporter__minimal_8cpp.html',1,'']]],
  ['result_5freporter_5fminimal_2eh',['result_reporter_minimal.h',['../result__reporter__minimal_8h.html',1,'']]],
  ['result_5freporter_5fplugin_5floader_5f',['result_reporter_plugin_loader_',['../classSimplex__method__calculator.html#aea86692b8031fcf12410327c32af1cf9',1,'Simplex_method_calculator']]],
  ['result_5freporter_5fplugin_5fmenu',['result_reporter_plugin_menu',['../classMainWindow.html#a7e9ebcb30a5c1b52b333667d1846c39b',1,'MainWindow']]],
  ['root_5fdir',['root_dir',['../classStartApp.html#aec43484cd57a1722eb328aef4f86f719',1,'StartApp']]]
];
